version: '3'

services:
  postgrestaxcalc:
    restart: always
    image: "postgres:9.5"
    container_name: postgrestaxcalc
    volumes:
      - "./database/:/docker-entrypoint-initdb.d/"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker

  taxcalc:
    restart: always
    image: "golang:1.11"
    container_name: taxcalc
    ports:
      - 9001:9001
    links:
      - postgrestaxcalc
    depends_on:
      - postgrestaxcalc
    environment:
      DBHOST: postgrestaxcalc
      DBUSER: docker
      DBPASS: docker
      DBNAME: docker
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./taxcalc

